import LegalLayout, { LegalSection } from '@/shared/components/LegalLayout'
import Seo from '@/shared/components/Seo'

const Terms = () => (
  <>
    <Seo title="Terms of Service" path="/terms" />
    <LegalLayout title="Terms of Service" lastUpdated="June 30, 2026">
    <LegalSection title="1. Acceptance of terms">
      <p>
        By creating an account or using GenSite ("the Service"), you agree to these Terms of Service.
        If you do not agree, please do not use the Service.
      </p>
    </LegalSection>

    <LegalSection title="2. Your account">
      <p>
        You must provide an accurate email address and are responsible for keeping your login credentials
        secure and for all activity under your account. You must be old enough to form a binding contract
        in your jurisdiction.
      </p>
    </LegalSection>

    <LegalSection title="3. Credits and payments">
      <p>
        The Service uses a credit system. Generating or revising a website consumes credits. You may purchase
        additional credits through our payment processor (Stripe). Prices and credit costs may change; changes
        apply to future purchases only.
      </p>
      <p>
        Purchased credits are generally non-refundable except where required by law. Credits have no cash value
        and are not transferable.
      </p>
    </LegalSection>

    <LegalSection title="4. AI-generated content">
      <p>
        Websites are generated by third-party AI models based on your prompts. Output may be inaccurate,
        incomplete, or similar to content generated for others. You are responsible for reviewing, testing,
        and ensuring your generated sites are lawful and do not infringe anyone's rights before publishing or
        using them.
      </p>
      <p>
        Subject to these Terms and any applicable model-provider terms, you are free to use the websites you
        generate. We claim no ownership of your prompts or generated output.
      </p>
    </LegalSection>

    <LegalSection title="5. Acceptable use">
      <p>You agree not to use the Service to create, host, or distribute content that is illegal, harmful,
        deceptive, infringing, or abusive, and not to attempt to disrupt, reverse-engineer, scrape, or overload
        the Service.</p>
    </LegalSection>

    <LegalSection title="6. Publishing and the community gallery">
      <p>
        If you choose to publish a project, it becomes publicly viewable (including via a shareable link and the
        community gallery). By publishing, you grant us a non-exclusive license to host and display that content
        for the purpose of operating the Service. You can unpublish at any time.
      </p>
    </LegalSection>

    <LegalSection title="7. Availability">
      <p>
        The Service is provided "as is" and "as available," without warranties of any kind. We do not guarantee
        uninterrupted access; the Service may experience downtime, delays (including cold starts), or limits
        from upstream AI providers.
      </p>
    </LegalSection>

    <LegalSection title="8. Termination">
      <p>
        You may delete your account at any time from your account settings, which removes your projects. We may
        suspend or terminate accounts that violate these Terms.
      </p>
    </LegalSection>

    <LegalSection title="9. Limitation of liability">
      <p>
        To the maximum extent permitted by law, GenSite and its operator are not liable for indirect,
        incidental, or consequential damages, or for any loss of data, profits, or content arising from your
        use of the Service.
      </p>
    </LegalSection>

    <LegalSection title="10. Changes to these terms">
      <p>We may update these Terms from time to time. Continued use after changes take effect constitutes
        acceptance of the revised Terms.</p>
    </LegalSection>

    <LegalSection title="11. Contact">
      <p>
        Questions? Contact{' '}
        <a className="text-indigo-400 hover:underline" href="mailto:prathameshprasad510@gmail.com">
          prathameshprasad510@gmail.com
        </a>.
      </p>
    </LegalSection>
    </LegalLayout>
  </>
)

export default Terms
