import { describe, it, expect } from 'vitest';
import { sanitizeHtml } from '../sanitize.js';

describe('sanitizeHtml', () => {
  it('preserves inline UI scripts generated by the LLM', () => {
    const input = '<html><head></head><body><script>document.getElementById("btn").click()</script><p>Clean content</p></body></html>';
    const output = sanitizeHtml(input);
    expect(output).toContain('document.getElementById("btn").click()');
    expect(output).toContain('<p>Clean content</p>');
  });

  it('preserves allowed CDN scripts like Tailwind browser CDN and AOS', () => {
    const input = '<html><head><script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script></head><body><script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script></body></html>';
    expect(sanitizeHtml(input)).toBe(input);
  });

  it('strips unknown external script sources, quoted or not', () => {
    const input = '<script src="http://evil.com/a.js"></script><script src=//evil.com/b.js></script><p>Content</p>';
    const output = sanitizeHtml(input);
    expect(output).not.toContain('evil.com');
    expect(output).toContain('<p>Content</p>');
  });

  it('does not let a lookalike host through', () => {
    const output = sanitizeHtml('<script src="https://cdn.jsdelivr.net.evil.com/x.js"></script>');
    expect(output).not.toContain('evil.com');
  });

  it('keeps interactive handlers the generated page relies on', () => {
    const input = '<button onclick="toggleMenu()">Menu</button>';
    expect(sanitizeHtml(input)).toBe(input);
  });

  it('never alters text content', () => {
    const input = '<p>Pick one = the best. Learn javascript: the good parts.</p><div data-onboarding="step1">hi</div>';
    expect(sanitizeHtml(input)).toBe(input);
  });

  it('neutralizes javascript: URLs in every quoting and casing form', () => {
    const cases = [
      '<a href="javascript:alert(1)">x</a>',
      "<a href='JaVaScRiPt:alert(1)'>x</a>",
      '<a href=javascript:alert(1)>x</a>',
      '<a href=" java&#x09;script:alert(1)">x</a>',
      '<form action="javascript:alert(1)"></form>',
      '<iframe src="data:text/html,<script>alert(1)</script>"></iframe>',
    ];
    for (const input of cases) {
      const output = sanitizeHtml(input);
      expect(output, input).not.toMatch(/javascript|data:text/i);
      expect(output, input).toContain('"#"');
    }
  });

  it('leaves safe URLs untouched', () => {
    const input = '<a href="#about">About</a><img src="https://images.pexels.com/x.jpg"><a href="mailto:a@b.com">m</a>';
    expect(sanitizeHtml(input)).toBe(input);
  });
});
